### ISSUE TITLE
Installer Crashing 

### ISSUE THREAD

**Issue by MarshMello0** [MarshMello0/VTOLVR-ModLoader#12]
**Describe the bug**
The installer keeps crashing before the user is able to install the mod loader

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the installer
2. Run the installer
3. Press next and it crashes

**Expected behaviour**
Continues onto next page where you select the folder

**Comment by MarshMello0** [comment]
Still Crashes if the game is installed
Still Crashes if the Reg Key is present (or not)

**Comment by ketkev** [comment]
It doesn't occur on my desktop while it crashes on my laptop

**Comment by ketkev** [comment]
It's throwing an IndexOutofRangeException in the FindVTOL() Method

**Comment by MarshMello0** [comment]
The issue was found at `string gameFolder = File.ReadAllText(regPath + @"\steamapps\libraryfolders.vdf").Split('"')[13];` by @ketkev 

Fixed by doing a check if the length is 13 or greater, if not, they are using the default steam path which has the .exe as well. Which is in the variable regPath.
