### ISSUE TITLE
Button to open pancake mod loader screen

### ISSUE THREAD

**Issue by nebriv** [MarshMello0/VTOLVR-ModLoader#40]
It'd be wonderful if there were a way to open the mod loading screen from the user's pancake screen. Similar to the Map/Mission editor buttons. Trying to avoid having to put my headset on while testing/debugging :)

Thanks guys!

**Comment by MarshMello0** [comment]
Issue resolved with adding the ablity to load mods, pilots and secnarios from the mod loaders settings page.
